### ISSUE TITLE
[watch-only] signer

### ISSUE THREAD

**Issue by motorina0** [motorina0/lnbits#10]
- [x] testnet PSBT parse fail: https://github.com/micro-bitcoin/uBitcoin/issues/18
- [x] add custom config
- [x] check fee difference
- [x] encrypt communication
- [x] encrypt at rest (with password)
- [x] check for buttons (next/back/ok)
### Todo
- [x] show version of firmware
- [x] show address on device
- [x] cannot spend to taproot -> warn message
- [x] xpub qrcode
- [x] address qrcode
- [x] show seed in browser (after encryption)
- [ ] Ubuntu pairing issue
- [x] add passphrase on login
   - [x] remove from `Restore`
   - [x] info message about seed 
- [ ] op_return (?)
- [x] safer word-list input
- [ ] change address not detected on HWW
- [ ] ~~session timeout after one hour~~

**Comment by motorina0** [comment]
Secure communication:
 - use ECDH to build the shared secret
 - use AES-CBC for symmetric encryption 

WHH side:
 - uBitcoin point multiplication for secret derivation
 - https://github.com/kokke/tiny-AES-c for encrypt/decrypt

Browser Side:
 - https://github.com/paulmillr/noble-secp256k1 for secret derivation
 - SubtleCrypto for encrypt/decrypt

**Comment by motorina0** [comment]
- [ ] test password with special characters (`?`)

**Comment by motorina0** [comment]
Tetris:
- https://github.com/VolosR/TTGOTetris/blob/main/TTgOTetris.ino?

**Comment by motorina0** [comment]
- [ ] PSBT checksum (check that the PSBT is not altered "in transit")
